version: '3.8'
services:
  # ms-broker:
  #   container_name: ms-broker
  #   image: rabbitmq:3-management-alpine
  #   environment:
  #     RABBITMQ_DEFAULT_USER: root
  #     RABBITMQ_DEFAULT_PASS: root
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   volumes:
  #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  #   networks:
  #     - ms-broker-network

  ms-api-broker:
    container_name: ms-api-broker
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - '2222:3000'
    environment:
      CORS_ORIGIN: "*"
      RABBITMQ_URL: amqp://root:root@broker:5672
    # depends_on:
    #   - ms-broker
    networks:
      - ms-broker-network

networks:
  ms-broker-network:
    name: BROKER
    # name: MS-BROKER
    # driver: bridge
