name: Build API Stack

on:
  - push
  - workflow_dispatch

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout action repository
        uses: actions/checkout@v3
        with:
          repository: heronlabs/build-node-install-action
          ref: 1.3.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS }}
          path: ./build-node-install-action

      - name: Run action
        uses: './build-node-install-action/application/github'
        with:
          AUTHOR_PERSONAL_ACCESS: ${{ secrets.AUTHOR_PERSONAL_ACCESS }}

      - name: Start RabbitMQ
        uses: namoshek/rabbitmq-github-action@v1
        with:
          version: '3.8.9'
          ports: '5672:5672'
          container-name: 'mqtt'

      - name: '[TEST] | Integration Tests'
        run: yarn test:integration --coverage
        shell: bash
