name: Build API Stack

on:
  - push
  - workflow_dispatch

jobs:
  pipeline:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:management
        env:
          RABBITMQ_DEFAULT_USER: 'root'
          RABBITMQ_DEFAULT_PASS: 'root'
          RABBITMQ_DEFAULT_VHOST: '/'
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v3

      - name: Checkout action repository
        uses: actions/checkout@v3
        with:
          repository: heronlabs/build-api-action
          ref: 1.4.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS}}
          path: ./build-api-action

      - name: Run action
        uses: './build-api-action/application/github'
        with:
          AUTHOR_PERSONAL_ACCESS: ${{ secrets.AUTHOR_PERSONAL_ACCESS }}
