name: Build API Stack

on:
  - push
  - workflow_dispatch

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout action repository
        uses: actions/checkout@v3
        with:
          repository: heronlabs/build-node-install-action
          ref: 1.3.0
          token: ${{ inputs.AUTHOR_PERSONAL_ACCESS }}
          path: ./build-node-install-action

      - name: Run action
        uses: './build-node-install-action/application/github'
        with:
          AUTHOR_PERSONAL_ACCESS: ${{ inputs.AUTHOR_PERSONAL_ACCESS }}

      - name: '[BUILD] | Compile'
        run: yarn compile
        shell: bash

      - name: '[TEST] | Lint Check'
        run: yarn lint:check
        shell: bash

      - name: '[TEST] | Unit Tests'
        run: yarn test:unit --coverage
        shell: bash

      - name: '[UP] | Up Broker'
        run: yarn docker:up:broker
        shell: bash

      - name: '[TEST] | Integration Tests'
        run: yarn test:integration --coverage
        shell: bash
